// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type DishDelivery struct {
	ID                 string         `json:"id"`
	SubscriptionDishID string         `json:"subscriptionDishID"`
	Status             string         `json:"status"`
	ExpectedTime       interface{}    `json:"expectedTime"`
	DeliveryTime       interface{}    `json:"deliveryTime"`
	Note               sql.NullString `json:"note"`
}

type Subscription struct {
	ID              string      `json:"id"`
	UserID          string      `json:"userID"`
	PlaylistID      string      `json:"playlistID"`
	Customized      bool        `json:"customized"`
	Status          string      `json:"status"`
	Frequency       string      `json:"frequency"`
	StartDate       interface{} `json:"startDate"`
	EndDate         interface{} `json:"endDate"`
	ReceiverName    string      `json:"receiverName"`
	ReceiverContact string      `json:"receiverContact"`
}

type SubscriptionDish struct {
	ID             string         `json:"id"`
	DishID         string         `json:"dishID"`
	SubscriptionID string         `json:"subscriptionID"`
	ScheduleTime   interface{}    `json:"scheduleTime"`
	Frequency      string         `json:"frequency"`
	DishOptions    string         `json:"dishOptions"`
	Note           sql.NullString `json:"note"`
}
